### ISSUE TITLE
Make sure all links we control to docs.simplifier.net get updated to docs.fire.ly 

### ISSUE THREAD

**Issue by wardweistra** [FirelyTeam/firely-docs#112]
Overview on https://firely.atlassian.net/wiki/spaces/SMPL/pages/173146140/Moving+product+documentation (visible to Firely only).
* Fixed for Forge in upcoming release: https://firely.atlassian.net/browse/FOR-478
* First pass for links in Simplifier code at: https://github.com/FirelyTeam/simplifier/pull/4

**Comment by wardweistra** [comment]
@rbouichrat I think this is resolved, right?

**Comment by rbouichrat** [comment]
I'd say so yes, and in case we've missed anything we will hear about it soon enough.

**Comment by wardweistra** [comment]
@rbouichrat: @mbaltus found a few more, can you take those on? https://firely.atlassian.net/wiki/spaces/SMPL/pages/173146140/Moving+product+documentation?focusedCommentId=538509329#comment-538509329

**Comment by wardweistra** [comment]
Seems fixed
